apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-credit-app
  labels:
    app: pi-credit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-credit
  template:
    metadata:
      labels:
        app: pi-credit
    spec:
      containers:
        - name: pi-credit-app
          image: pi-credit-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
