apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: picredit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: REPLACE_ME_ECR_IMAGE   # CI will push image and you will replace this before `kubectl apply`
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef:    { name: db-credentials }
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }

