apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-credit
  namespace: pi-credit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-credit
  template:
    metadata:
      labels:
        app: pi-credit
    spec:
      containers:
        - name: pi-credit
          image: pi-credit-app:latest   # built and imported by GitHub Actions
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: pg-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
