---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: pi-credit
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASSWORD: pass123
  DB_NAME: picredit

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: pi-credit
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pi-credit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - secretKeyRef:
                - name: DB_USER
                  value: appuser
                - name: DB_PASSWORD
                  value: pass123
                - name: DB_NAME
                  value: picredit
                
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
