version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: picredit
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U appuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: pi-credit-app:local
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: picredit
      DB_USER: appuser
      DB_PASSWORD: pass123
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

